# Generated by Django 4.2.19 on 2025-02-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('pub_date', models.DateField()),
                ('body', models.TextField()),
                ('job_img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
